language:
  - python

sudo:
  - required

dist:
  - xenial

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libzbar0 python-opencv

install:
  - pip install tox-travis coveralls

script:
  - tox

after_success:
  - coveralls
